#index:
#    path: /
#    controller: App\Controller\DefaultController::index

recipe_create:
  path: /recipe/new
  controller: App\Controller\RecipeController::create

recipe_read:
  path: /recipe/{id}
  controller: App\Controller\RecipeController::read

recipe_update:
  path: /recipe/{id}/update
  controller: App\Controller\RecipeController::update

recipe_delete:
  path: /recipe/{id}/delete
  controller: App\Controller\RecipeController::delete
