#index:
#    path: /
#    controller: App\Controller\DefaultController::index

recipe_create:
  path: /recipe/new
  controller: App\Controller\RecipeController::create

recipe_read:
  path: /recipe/{id}
  controller: App\Controller\RecipeController::read
