recipe_create:
  path: /recipes/new
  controller: App\Controller\RecipeController::create
  methods: POST

recipe_read:
  path: /recipes/{id}
  controller: App\Controller\RecipeController::read
  methods: GET

recipe_update:
  path: /recipes/{id}
  controller: App\Controller\RecipeController::update
  methods: POST

recipe_delete:
  path: /recipes/{id}
  controller: App\Controller\RecipeController::delete
  methods: DELETE

recipe_all:
  path: /recipes
  controller: App\Controller\RecipeController::all
  methods: GET

recipe_list:
  path: /recipes/list
  controller: App\Controller\RecipeController::list
  methods: GET

